[default]
    check-filename = false
    unicode = true
    # Ignore code spans
    extend-ignore-re = ["(?s)^.*?`[^`]+`.*$"]

[default.extend-words]
        "Noice" = "Noice"

[files]
    extend-exclude = [
        "typos.toml",
        "**/.git*",
        "*.csv",
        "*.js",
        "**/package-lock.json",
        "**/node-modules/**",
        "**/vscodeextension/**",
        "**/.git/objects/**",
        "**/.vscode/**",
        "**/.vscode-insiders/**",
        "**/.tmp-projections/**",
        "**/*.interactive",
    ]
